trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
      - job: JOB1
        steps:
          - script: echo Syncing the code!

      - job: JOB2
        dependsOn: JOB1
        steps:
          - script: echo Compiling the code!

  - stage: Test
    dependsOn: Build
    jobs:
      - job: JOB1
        steps:
          - script: echo Testing the code!

  - stage: DevDeploy
    dependsOn: Test
    jobs:
      - job: JOB1
        steps:
          - script: echo DevDeploy the code!

  - stage: QADeploy
    dependsOn: Test
    jobs:
      - job: JOB1
        steps:
          - script: echo QADeploy the code!

  - stage: ProdDeploy
    dependsOn: Test
    jobs:
      - job: JOB1
        steps:
          - script: echo ProdDeploy the code!
